spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/user?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    hikari:
      idle-timeout: 300000
      max-lifetime: 1800000
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    output:
      ansi.enabled: always
    servlet:
      multipart:
        max-file-size: 1GB
        max-request-size: 1GB
  data:
    redis:
      port: 6379
      host: ${REDIS_URL}
logging:
  level:
    org.springframework.data.redis.cache: DEBUG
jwt:
  secret: ${JWT_SECRET}
server:
  port: 8080
service:
  tale:
    url: ${TALE_URL}
