apiVersion: v1
kind: Service
metadata:
  name: tosi-db-user-svc
spec:
  selector:
    app: tosi
    tier: database
  ports:
    - port: 3306 # mysql과 동일 포트로 연결해야 함
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tosi-db-user-dep
spec:
  replicas: 1 # 데이터베이스는 replica로 복제할 수 없음
  selector:
    matchLabels:
      app: tosi
      tier: database
  template:
    metadata:
      labels:
        app: tosi
        tier: database
    spec:
      containers:
        - name: tosi-db-user
          image: mysql:8.4
          volumeMounts:
            - name: tosi-db-user-vol # configmap에 정의해둔 init.sql 실행
              mountPath: /docker-entrypoint-initdb.d
          envFrom:
            - secretRef: # mysql 인증정보
                name: tosi-db-user-scrt

      volumes:
        - name: tosi-db-user-vol
          configMap:
            name: tosi-db-user-configmap
