apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tosi-ebs-sc
# https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/ebs-csi.html # eks add-on에 ebs csi 연결해야 함
provisioner: ebs.csi.aws.com # eks cluster에서 add-on 으로 추가한 드라이버 -> pvc가 요구하는 pv(ebs 볼륨) 자동생성(동적 프로비저닝)
volumeBindingMode: WaitForFirstConsumer # pod 배치까지 볼륨 바인딩 지연
parameters:
  csi.storage.k8s.io/fstype: ext4 # file system type
  type: gp2 # general purpose ssd
  encrypted: "true" # 볼륨 암호화
# 가용 영역 자동 배치
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # ebs는 하나의 ec2(노드)만 연결할 수 있어서 ReadWriteMany 불가
  storageClassName: tosi-ebs-sc
  resources:
    requests:
      storage: 5Gi
