apiVersion: v1
kind: Service
metadata:
  name: tosi-user-service
spec:
  selector:
    app: tosi
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tosi-user-deployment
spec:
  selector:
    matchLabels:
      app: tosi
      tier: backend
  template:
    metadata:
      labels:
        app: tosi
        tier: backend
    spec:
      replicas: 2
      containers:
        - name: tosi-be-user
          image: dyckerkim/tosi-be-user:latest
