name: USER CI

# develop 브랜치에 push 되면
on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 액션 시작
      - name: Checkout code
        uses: actions/checkout@v4

        # 자바 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

        # 그래들 설치
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

        # 그래들 권한 설정 후 빌드
      - name: Build with Gradle
        run: |
          cd user
          chmod +x ./gradlew 
          ./gradlew build -x test
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          MYSQL_URL: 127.0.0.1
          REDIS_URL: localhost
          TALE_URL: http://localhost:8080/api/tales
          JWT_SECRET: jwtsecretfortest
