name: USER CD

# release로 시작하는 브랜치에 push될 때
on:
  push:
    branches: ["release-*"]

# 깃헙 토큰 권한 생성
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 액션 시작
      - name: Checkout code
        uses: actions/checkout@v4

      # 도커 이미지 생성(buildx 방식이 빠름)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 도커 허브 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      # 커밋 번호를 태그로 지정
      # 현재 이미지를 최신 이미지로 지정
      - name: Build and Push Docker Image
        run: |
          cd user
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/tosi-be-user:${{ github.sha }} --push .
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/tosi-be-user:latest --push .

      # aws 인증
      # aws에 github actions용 role 생성 후 eks access에 추가
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubTokenEKSRole

      # kubectl을 TOSI 클러스터와 연결
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name TOSI

      # user pod을 재시작하여 최신 이미지 pull
      - name: Deploy
        run: kubectl rollout restart deployment/tosi-user-dep
